name: "Street Fighter III: Third Strike"
sha1: ac99c97e9379bc4ac865c0f076a48ae543f127a9
options:
  basename: SLPM_656.21
  target_path: ../SLPM_656.21
  base_path: .
  platform: ps2
  compiler: MWCCPS2
  asm_path: ../asm
  src_path: ../src
  asset_path: ../assets
  build_path: ../build
  find_file_boundaries: True
  section_order: [".text", ".data", ".rodata", ".bss"]
  subalign: null
  migrate_rodata_to_functions: False
  find_file_boundaries: False
  # disasm_unknown: True
  # named_regs_for_c_funcs: False
  gp_value: 0x004F9B70
  ld_bss_is_noload: False
  rodata_string_guesser_level: 0 # without this some rodata gets too much alignment

segments:
  - [0x0, pad]

  - name: main
    type: code
    start: 0x00000080
    vram: 0x00100000
    bss_size: 0x16D870
    align: 128
    subalign: 4
    subsegments:
    - [0x000080, asm, sdk/crt0]
    - [0x0002B0, asm, sdk/libgraph/graph001]
    - [0x000450, asm, sdk/libgraph/graph002]
    - [0x0004B8, asm, sdk/libgraph/graph011]
    - [0x000550, asm, sdk/libgraph/graph012]
    - [0x000868, asm, sdk/libgraph/graph015]
    - [0x000A50, asm, sdk/libgraph/graph017]
    - [0x000BD0, asm, sdk/libgraph/graph019]
    - [0x000C70, asm, sdk/libdma/libdma]
    - [0x0014B8, asm, sdk/libvu0/libvu0]
    - [0x002C00, asm, sdk/libkernl/klib]
    - [0x0034A0, asm, sdk/libkernl/glue]
    - [0x003870, asm, sdk/libkernl/cache]
    - [0x003AF0, asm, sdk/libkernl/intr]
    - [0x003D20, asm, sdk/libkernl/thread]
    - [0x004170, asm, sdk/libkernl/deci2]
    - [0x0043A8, asm, sdk/libkernl/tty]
    - [0x0048F0, asm, sdk/libkernl/kprintf2]
    - [0x0052A8, asm, sdk/libkernl/sifcmd]
    - [0x005A84, asm, sdk/libkernl/sifrpc]
    - [0x006B70, asm, sdk/libkernl/filestub]
    - [0x00A228, asm, sdk/libkernl/iopheap]
    - [0x00A778, asm, sdk/libkernl/eeloadfile]
    - [0x00B4D8, asm, sdk/libkernl/iopreset]
    - [0x00B7B8, asm, sdk/libkernl/tlbfunc]
    - [0x00BD00, asm, sdk/libkernl/tlbtrap]
    - [0x00C060, asm, sdk/libkernl/diei]
    - [0x00C0D0, asm, sdk/libkernl/initsys]
    - [0x00C360, asm, sdk/libkernl/libosd]
    - [0x00C4E0, asm, sdk/libkernl/exit]
    - [0x00C780, asm, sdk/libkernl/alarm]
    - [0x00C8C0, asm, sdk/libkernl/timer]
    - [0x00DC28, asm, sdk/libkernl/timeralarm]
    - [0x00E018, asm, sdk/libkernl/iopnotify]
    - [0x00E278, asm, sdk/libcdvd/cdvd000]
    - [0x00F7D0, asm, sdk/libcdvd/cdvd005]
    - [0x00F9B0, asm, sdk/libcdvd/cdvd010]
    - [0x00FA80, asm, sdk/libcdvd/cdvd014]
    - [0x00FB18, asm, sdk/libcdvd/cdvd015]
    - [0x00FBB0, asm, sdk/libcdvd/cdvd018]
    - [0x00FC68, asm, sdk/libcdvd/cdvd036]
    - [0x00FD38, asm, sdk/libmc/libmc] # May continue below 👇

    - [0x011538, asm]

    - [0x0AB6F0, c, sfiii/1AB670]
    - [0x0AB70C, pad]
    - [0x0AB710, asm]

    - [0x0DB4C0, asm, sfiii/options/sound/draw_track_name]

    - [0x0DB5F0, asm]

    - [0x120870, c, sfiii/2207F0]

    - [0x12090C, pad]
    - [0x120910, asm]

    - [0x271930, asm, sfiii/game_loop]
    - [0x271D08, asm, sfiii/pad/371C88]
    - [0x271D88, asm, sfiii/pad/vibration]
    - [0x271E80, c, sfiii/main]

    - [0x271EA0, asm]

    - [0x274F60, asm, gcc/libc/memchr]
    - [0x275040, asm, gcc/libc/memcmp]
    - [0x2750D8, asm, gcc/libc/memcpy]
    - [0x275188, asm, gcc/libc/memmove]
    - [0x275290, asm, gcc/libc/memset]

    - [0x275350, asm]

    - [0x276920, asm, gcc/libc/strcat]
    - [0x276A50, asm, gcc/libc/strchr]
    - [0x276BE0, asm, gcc/libc/strcmp]
    - [0x276D28, asm, gcc/libc/strcpy]
    - [0x276E40, asm, gcc/libc/strlen]
    - [0x276F78, asm, gcc/libc/strncat]
    - [0x277128, asm, gcc/libc/strncmp]
    - [0x2772E0, asm, gcc/libc/strncpy]

    - [0x2774A0, asm]

    - [0x284810, asm, sfiii/pad/384790]

    - [0x285370, asm]

    - [0x286800, asm, sdk/libdbc/libdbc]
    - [0x287720, asm, sdk/libpad2/libpad2]

    - [0x287FE0, asm]

    # Data

    - [0x295200, data]

    - [0x2E7580, data, sdk/libgraph/graph001]
    - [0x2E75A0, data, sdk/libgraph/graph002]
    - [0x2E75C0, data, sdk/libdma/libdma]
    - [0x2E75F8, pad]
    - [0x2E7600, data, sdk/libvu0/libvu0]
    - [0x2E7640, data, sdk/libkernl/klib]
    - [0x2E7650, data, sdk/libkernl/glue]
    - [0x2E7658, data, sdk/libkernl/thread]
    - [0x2E765C, pad]
    - [0x2E7660, data, sdk/libkernl/kprintf2]
    - [0x2E7668, data, sdk/libkernl/sifcmd]
    - [0x2E766C, pad]
    - [0x2E7670, data, sdk/libkernl/sifrpc]
    - [0x2E7674, pad]
    - [0x2E7678, data, sdk/libkernl/filestub]
    - [0x2E7718, data, sdk/libkernl/iopheap]
    - [0x2E771C, pad]
    - [0x2E7720, data, sdk/libkernl/eeloadfile]
    - [0x2E7728, data, sdk/libkernl/tlbfunc]
    - [0x2E7D78, data, sdk/libkernl/initsys]
    - [0x2E7D98, data, sdk/libkernl/libosd]
    - [0x2E8558, data, sdk/libkernl/exit]
    - [0x2E8560, data, sdk/libkernl/alarm]
    - [0x2E8D08, data, sdk/libkernl/timer]
    - [0x2E8D28, data, sdk/libkernl/iopnotify]
    - [0x2E8D30, pad]
    - [0x2E8D40, data, sdk/libcdvd/cdvd000]
    - [0x2EA8E8, data, sdk/libcdvd/cdvd036]
    - [0x2EA8F4, pad]
    - [0x2EA8F8, data, sdk/libmc/libmc] # May continue below 👇

    - [0x2EAAE0, data]

    - [0x3455F0, data, sdk/libdbc/libdbc]
    - [0x345608, data, sdk/libpad2/libpad2]

    - [0x345638, data]

    # Rodata

    - [0x359680, rodata, sdk/libgraph/graph012]
    - [0x359810, rodata, sdk/libgraph/graph015]
    - [0x359930, rodata, sdk/libgraph/graph017]
    - [0x359968, rodata, sdk/libdma/libdma]
    - [0x3599D2, pad]
    - [0x3599D8, rodata, sdk/libkernl/thread]
    - [0x359A10, rodata, sdk/libkernl/tty]
    - [0x359A80, rodata, sdk/libkernl/kprintf2]
    - [0x359BD4, pad]
    - [0x359BE0, rodata, sdk/libkernl/filestub]
    - [0x359C48, rodata, sdk/libkernl/eeloadfile]
    - [0x359C60, rodata, sdk/libkernl/iopreset]
    - [0x359C90, rodata, sdk/libkernl/tlbfunc]
    - [0x359D10, rodata, sdk/libkernl/exit]
    - [0x359D18, rodata, sdk/libcdvd/cdvd000]
    - [0x359EE8, rodata, sdk/libcdvd/cdvd005]
    - [0x359F10, rodata, sdk/libmc/libmc]

    - [0x359F98, rodata]
    - [0x3DE010, rodata]
    - [0x3DE040, rodata]

    - [0x3F0130, rodata, sdk/libdbc/libdbc]
    - [0x3F03A0, rodata, sdk/libpad2/libpad2] # May need to end a bit sooner

    - [0x3F0400, rodata]

  - [0x3F85AD]
