name: Build and check

on:
    push:
        branches: [ "main" ]
    pull_request:
        branches: [ "main" ]
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - name: Install Python dependencies
              run: pip install -r tools/requirements-python.txt

            - name: Install Linux dependencies
              run: sudo apt-get update && sudo apt-get install -y $(cat tools/requirements-debian.txt)

            - name: Setup build tools
              run: make setup_tools
            
            - name: Decrypt original ELF's binary
              run: openssl enc -d -aes-256-cbc -in encrypted.bin -out THIRD_U.BIN -pass pass:${{ secrets.BIN_PASSWORD }}
            
            - name: Print original ELF's SHA
              run: shasum -a 256 THIRD_U.BIN
