name: Build and check

on:
    push:
        branches: [ "main" ]
    pull_request:
        branches: [ "main" ]
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - name: Install Python dependencies
              run: pip install -r tools/requirements-python.txt

            - name: Install Linux dependencies
              run: sudo apt-get update && sudo apt-get install -y $(cat tools/requirements-debian.txt)

            - name: Setup build tools
              run: make setup_tools
            
            - name: Download and unzip the image
              run: curl -L -o image.7z ${{ secrets.IMAGE_URL }} && 7z x image.7z
            
            - name: Print original ELF's SHA
              run: shasum -a 256 THIRD_U.BIN
